 // NOTE: pure data module — no imports; imported by scripts/seed.mjs.

// VELORA EDIT catalog v2 — exactly 100 curated demo records.
// 20 rings / 20 necklaces / 15 bracelets / 15 earrings / 10 chains = 80,
// of which gender men = 10 and gender unisex = 10 (counted across categories).
// All 30 legacy slugs are preserved so journal links and bookmarks keep working.

const GOLD = 'Gold-tone stainless steel';
const SILVER = 'Silver-tone stainless steel';
const BLACK = 'Black ion-plated stainless steel';
const GALLOY = 'Gold-tone alloy, nickel-free posts';
const SALLOY = 'Silver-tone alloy, nickel-free posts';
const PEARL_G = 'Glass pearl, gold-tone posts';
const PEARL_S = 'Glass pearl, silver-tone posts';

// n: display name | s: slug | c: category | g: gender | col: color | mat: material
// p: price | coll: collections | t: tags | F: featured(signature) | N: new | B: best value | L: limited | P: editor pick
// sc: editorial score | d: description | note: editor note
const R = [
 // ---------------- RINGS (20) ----------------
 { n:'Noir Signet', s:'noir-signet', c:'rings', g:'men', col:'black', mat:BLACK, p:14.90, coll:['quiet-luxury','for-him','everyday','best-value','signature','minimal-essentials'], t:['signet','minimal','men','modern','clean'], F:1,N:0,B:1,L:0,P:1, sc:92, d:'A black signet with a flat face and softened edges — structured on the hand without feeling heavy.', note:'Our most borrowed men’s piece: it reads tailored with everything from a white tee to a dark suit.' },
 { n:'Luna Ring', s:'luna-ring', c:'rings', g:'women', col:'gold', mat:GOLD, p:11.40, coll:['minimal-essentials','gold-edit','under-20','for-her','everyday','minimal-gold'], t:['band','minimal','gold-tone','women','everyday'], F:0,N:1,B:0,L:0,P:0, sc:88, d:'A slender gold-tone band with a moon-soft curve — the ring you stop noticing, in the best way.', note:'A clean silhouette that works effortlessly on its own.' },
 { n:'Mira Ring', s:'mira-ring', c:'rings', g:'women', col:'silver', mat:SILVER, p:12.60, coll:['silver-essentials','silver-edit','under-20','everyday'], t:['stacking','minimal','silver','women','layering'], F:0,N:1,B:0,L:0,P:0, sc:84, d:'A cool silver stacking band, thin enough to pair and smooth enough to wear solo.', note:'Made for layering without overwhelming the rest of the look.' },
 { n:'Sceau Ring', s:'sceau-ring', c:'rings', g:'men', col:'gold', mat:GOLD, p:16.10, coll:['for-him','quiet-luxury','signature'], t:['signet','men','classic','gold-tone','clean'], F:1,N:0,B:0,L:0,P:0, sc:83, d:'A compact gold-tone signet with a brushed face — old-world shape, modern restraint.', note:'One strong piece is enough; this one carries the hand on its own.' },
 { n:'Anneau Double', s:'anneau-double', c:'rings', g:'women', col:'gold', mat:GOLD, p:13.80, coll:['minimal-essentials','gold-edit','everyday','minimal-gold'], t:['stacking','minimal','gold-tone','women','modern'], F:0,N:0,B:0,L:0,P:0, sc:81, d:'Two fine bands joined as one — the look of a stack with none of the spinning.', note:'A simple piece with just enough presence.' },
 { n:'Dôme Ring', s:'dome-ring', c:'rings', g:'women', col:'gold', mat:GOLD, p:17.90, coll:['quiet-luxury','date-night','signature','statement','for-her'], t:['dome','statement','gold-tone','women','date-night'], F:1,N:0,B:0,L:0,P:1, sc:87, d:'A low polished dome that catches light as you move — quiet from afar, rich up close.', note:'Chosen for finish: the curve is even, the shine is soft, nothing shouts.' },
 { n:'Bague Fine', s:'bague-fine', c:'rings', g:'women', col:'gold', mat:GOLD, p:9.90, coll:['under-20','best-value','everyday','minimal-essentials'], t:['band','minimal','gold-tone','women','gift'], F:0,N:0,B:1,L:0,P:0, sc:84, d:'The thinnest band in the edit — barely there, and exactly right with a watch.', note:'Proof that proportion matters more than price.' },
 { n:'Céline Band', s:'celine-band', c:'rings', g:'women', col:'gold', mat:GOLD, p:8.90, coll:['under-20','best-value'], t:['band','minimal','gold-tone','women','everyday'], F:0,N:0,B:1,L:0,P:0, sc:81, d:'A featherweight gold-tone band with a clean finish — buy one, or three for a stack.', note:'The strongest look per euro in the band drawer.' },
 { n:'Iris Band', s:'iris-band', c:'rings', g:'women', col:'silver', mat:SILVER, p:12.90, coll:['silver-essentials','silver-edit','under-20','for-her'], t:['band','minimalist','silver','women','office'], F:0,N:1,B:0,L:0,P:0, sc:85, d:'A cool, narrow silver band with softly rounded edges — office-quiet, weekend-easy.', note:'Silver keeps everything honest; this is the everyday anchor.' },
 { n:'Noma Ring', s:'noma-ring', c:'rings', g:'unisex', col:'silver', mat:SILVER, p:14.20, coll:['unisex','minimal-essentials','silver-edit','quiet-luxury'], t:['geometric','minimal','silver','unisex','modern'], F:0,N:0,B:0,L:0,P:0, sc:83, d:'A squared-off silver band with architectural lines — designed to suit any hand.', note:'Geometry does the talking so the outfit doesn’t have to.' },
 { n:'Arden Signet', s:'arden-signet', c:'rings', g:'men', col:'silver', mat:SILVER, p:19.90, coll:['for-him','quiet-luxury','gift-edit','silver-edit'], t:['signet','men','classic','silver','gift'], F:0,N:0,B:0,L:0,P:0, sc:86, d:'A cool-toned signet with a matte face and polished rim — heritage shape, contemporary mood.', note:'An easy gift: timeless shape, no sizing drama, no logos.' },
 { n:'Sélène Ring', s:'selene-ring', c:'rings', g:'women', col:'gold', mat:GOLD, p:15.60, coll:['gold-edit','date-night','for-her','minimal-gold'], t:['minimal','gold-tone','women','date-night','clean'], F:0,N:1,B:0,L:0,P:0, sc:84, d:'A softly hammered gold-tone band that scatters candlelight beautifully.', note:'Low light loves soft metal — this is a date-night quiet star.' },
 { n:'Ona Ring', s:'ona-ring', c:'rings', g:'women', col:'gold', mat:GOLD, p:13.20, coll:['gold-edit','under-20','everyday'], t:['organic','minimal','gold-tone','women','casual'], F:0,N:0,B:0,L:0,P:0, sc:82, d:'A gently irregular band with an organic, hand-touched feel — no two catch light alike.', note:'For those who find perfect polish a little boring.' },
 { n:'Vesper Band', s:'vesper-band', c:'rings', g:'women', col:'black', mat:BLACK, p:11.90, coll:['under-20','quiet-luxury','minimal-essentials'], t:['band','minimal','women','modern','clean'], F:0,N:0,B:0,L:0,P:0, sc:82, d:'A slim black band with a satin finish — unexpectedly versatile against everything.', note:'Black reads as a neutral once you try it; start here.' },
 { n:'Odette Ring', s:'odette-ring', c:'rings', g:'women', col:'silver', mat:SILVER, p:16.40, coll:['silver-essentials','silver-edit','gift-edit','for-her'], t:['twisted','silver','women','gift','classic'], F:0,N:0,B:0,L:0,P:0, sc:83, d:'A twisted silver band with rope-like detail — texture without bulk.', note:'Detail people will notice from a handshake away.' },
 { n:'Ronan Signet', s:'ronan-signet', c:'rings', g:'men', col:'gold', mat:GOLD, p:21.50, coll:['for-him','statement','date-night'], t:['signet','men','bold','gold-tone','statement'], F:0,N:0,B:0,L:1,P:0, sc:85, d:'A weightier gold-tone signet with a high-polish face — the confident end of the edit.', note:'Limited edit: a bolder cut for evenings that matter.' },
 { n:'Isolde Stack', s:'isolde-stack', c:'rings', g:'women', col:'gold', mat:GOLD, p:18.75, coll:['gold-edit','for-her','gift-edit','minimal-gold'], t:['stacking','gold-tone','women','layering','gift'], F:0,N:1,B:0,L:0,P:0, sc:86, d:'Three graduated gold-tone bands worn as one — a ready-made stack, perfectly spaced.', note:'For the indecisive stacker: someone already did the spacing for you.' },
 { n:'Alba Ring', s:'alba-ring', c:'rings', g:'women', col:'silver', mat:SILVER, p:10.40, coll:['silver-essentials','silver-edit','under-20'], t:['minimal','silver','women','everyday','clean'], F:0,N:0,B:0,L:0,P:0, sc:80, d:'A bright, smooth silver band with mirror edges — crisp against knitwear and denim.', note:'The white-tee equivalent of a ring.' },
 { n:'Cyr Ring', s:'cyr-ring', c:'rings', g:'unisex', col:'black', mat:BLACK, p:13.50, coll:['unisex','quiet-luxury','minimal-essentials'], t:['minimal','unisex','modern','clean','casual'], F:0,N:0,B:0,L:0,P:0, sc:81, d:'A matte black unisex band with a flat profile — sits calmly on any finger.', note:'Shared-jewelry approved: one size logic, zero fuss.' },
 { n:'Lucienne Ring', s:'lucienne-ring', c:'rings', g:'women', col:'gold', mat:GOLD, p:24.90, coll:['gold-edit','statement','date-night','signature'], t:['sculptural','statement','gold-tone','women','bold'], F:1,N:0,B:0,L:1,P:1, sc:90, d:'A sculptural gold-tone ring with folded planes — miniature architecture for the hand.', note:'Limited edit: the piece strangers ask about.' },
 // ---------------- NECKLACES (20) ----------------
 { n:'Aster Necklace', s:'aster-necklace', c:'necklaces', g:'women', col:'gold', mat:GOLD, p:21.50, coll:['gold-edit','date-night','for-her','statement','signature','minimal-gold'], t:['statement','pendant','gold-tone','women','date-night'], F:1,N:0,B:0,L:0,P:1, sc:85, d:'A star-set pendant on a fine gold-tone chain — evening polish without evening effort.', note:'The kind of piece that works without asking for attention.' },
 { n:'Arc Pendant', s:'arc-pendant', c:'necklaces', g:'women', col:'gold', mat:GOLD, p:16.90, coll:['minimal-essentials','gold-edit','under-20','for-her','minimal-gold'], t:['pendant','minimal','gold-tone','women','layering'], F:0,N:0,B:0,L:0,P:1, sc:89, d:'A single curved bar on a whisper-fine chain — minimalism with a point of view.', note:'Layers with everything and competes with nothing.' },
 { n:'Col Sertie', s:'col-sertie', c:'necklaces', g:'women', col:'gold', mat:GOLD, p:19.40, coll:['date-night','gold-edit','minimal-gold','new-arrivals'], t:['necklace','gold-tone','women','date-night','modern'], F:0,N:1,B:0,L:0,P:0, sc:85, d:'A close-sitting gold-tone collar line with a set stone accent — neat at every neckline.', note:'Made to sit exactly where necklines end.' },
 { n:'Vela Pendant', s:'vela-pendant', c:'necklaces', g:'women', col:'silver', mat:SILVER, p:14.20, coll:['silver-essentials','silver-edit','under-20'], t:['pendant','silver','women','minimal','everyday'], F:0,N:0,B:0,L:0,P:0, sc:80, d:'A small sail-shaped silver pendant — light, bright, and quietly nautical.', note:'A Monday necklace: unfussy, bright, done.' },
 { n:'Soleil Pendant', s:'soleil-pendant', c:'necklaces', g:'women', col:'gold', mat:GOLD, p:15.20, coll:['gift-edit','for-her','gold-edit'], t:['pendant','gold-tone','women','gift','classic'], F:0,N:0,B:0,L:0,P:0, sc:83, d:'A sun-disc pendant in warm gold-tone — cheerful without being loud.', note:'Gives gold-hoop energy to people who prefer necklaces.' },
 { n:'Mira Pendant', s:'mira-pendant', c:'necklaces', g:'women', col:'silver', mat:SILVER, p:13.90, coll:['silver-essentials','silver-edit','under-20','minimal-essentials'], t:['minimal','silver','women','layering','clean'], F:0,N:1,B:0,L:0,P:0, sc:84, d:'A tiny polished disc on a fine silver chain — the pendant equivalent of a deep breath.', note:'If you own one necklace, make it this quiet.' },
 { n:'Céleste Pendant', s:'celeste-pendant', c:'necklaces', g:'women', col:'gold', mat:GOLD, p:17.42, coll:['gold-edit','for-her','date-night'], t:['pendant','gold-tone','women','modern','date-night'], F:0,N:0,B:0,L:0,P:0, sc:85, d:'A crescent pendant with a soft brushed glow — celestial, but make it wearable.', note:'For dreamers with minimalist wardrobes.' },
 { n:'Iva Necklace', s:'iva-necklace', c:'necklaces', g:'women', col:'silver', mat:SILVER, p:12.20, coll:['silver-essentials','silver-edit','under-20','office'], t:['minimal','silver','women','office','everyday'], F:0,N:0,B:1,L:0,P:0, sc:83, d:'An extra-fine silver chain with a barely-there bead — professionalism, distilled.', note:'Passes every office dress code ever written.' },
 { n:'Théa Lariat', s:'thea-lariat', c:'necklaces', g:'women', col:'gold', mat:GOLD, p:22.90, coll:['gold-edit','statement','date-night','for-her'], t:['lariat','statement','gold-tone','women','bold'], F:0,N:0,B:0,L:0,P:0, sc:84, d:'A Y-shaped lariat that lengthens the neckline — adjustable drama, zero clasps to fight.', note:'The longest line in the edit, and the most flattering.' },
 { n:'Noor Necklace', s:'noor-necklace', c:'necklaces', g:'women', col:'gold', mat:GOLD, p:18.90, coll:['gold-edit','for-her','gift-edit'], t:['beaded','gold-tone','women','gift','classic'], F:0,N:0,B:0,L:0,P:0, sc:82, d:'Small polished gold-tone beads strung close — warmth you can wear daily.', note:'Beads, but make them grown-up.' },
 { n:'Cassia Pendant', s:'cassia-pendant', c:'necklaces', g:'women', col:'silver', mat:SILVER, p:15.75, coll:['silver-essentials','silver-edit','minimal-essentials'], t:['geometric','silver','women','modern','clean'], F:0,N:1,B:0,L:0,P:0, sc:83, d:'A hexagonal silver pendant with crisp edges — geometry that flatters soft knitwear.', note:'Sharp shape, soft styling: the contrast is the point.' },
 { n:'Alden Pendant', s:'alden-pendant', c:'necklaces', g:'men', col:'silver', mat:SILVER, p:24.50, coll:['for-him','silver-edit','gift-edit','quiet-luxury'], t:['pendant','men','silver','minimal','gift'], F:0,N:0,B:0,L:0,P:0, sc:85, d:'A slim silver tag pendant on a sturdy chain — masculine without motocross energy.', note:'The gateway pendant for the necklace-curious.' },
 { n:'Marc Pendant', s:'marc-pendant', c:'necklaces', g:'men', col:'black', mat:BLACK, p:19.95, coll:['for-him','quiet-luxury','under-20'], t:['pendant','men','modern','clean','casual'], F:0,N:0,B:0,L:0,P:0, sc:82, d:'A matte black pendant with a single polished edge — subtle from distance, sharp up close.', note:'Black-on-black’s best friend.' },
 { n:'Juno Necklace', s:'juno-necklace', c:'necklaces', g:'unisex', col:'silver', mat:SILVER, p:16.90, coll:['unisex','silver-edit','everyday','minimal-essentials'], t:['beaded','silver','unisex','casual','layering'], F:0,N:0,B:0,L:0,P:0, sc:82, d:'Small silver beads on a strong cord-look chain — borrowed-from-anyone energy.', note:'The communal necklace: looks right on everybody.' },
 { n:'RhÉa Pendant', s:'rhea-pendant', c:'necklaces', g:'unisex', col:'gold', mat:GOLD, p:17.25, coll:['unisex','gold-edit','layering','everyday'], t:['coin','gold-tone','unisex','layering','vintage'], F:0,N:1,B:0,L:0,P:0, sc:84, d:'A coin-style gold-tone pendant with a worn-soft relief — vintage mood, current proportions.', note:'History-buff style without the museum gift-shop vibe.' },
 { n:'Aeon Necklace', s:'aeon-necklace', c:'necklaces', g:'unisex', col:'black', mat:BLACK, p:14.50, coll:['unisex','quiet-luxury','minimal-essentials'], t:['minimal','unisex','modern','clean','casual'], F:0,N:0,B:0,L:0,P:0, sc:81, d:'A black cord-style necklace with a steel accent — the minimalist’s uniform finisher.', note:'Disappears into streetwear, sharpens tailoring.' },
 { n:'Opale Necklace', s:'opale-necklace', c:'necklaces', g:'women', col:'white', mat:PEARL_S, p:18.20, coll:['for-her','gift-edit','date-night'], t:['pearl','women','gift','classic','date-night'], F:0,N:0,B:0,L:0,P:0, sc:83, d:'A milky glass cabochon on silver-tone — opalescence on an everyday budget.', note:'Bridal-party pretty, Tuesday-afternoon easy.' },
 { n:'Liora Necklace', s:'liora-necklace', c:'necklaces', g:'women', col:'gold', mat:GOLD, p:23.40, coll:['gold-edit','layering','for-her','statement'], t:['layering','gold-tone','women','statement','modern'], F:0,N:0,B:0,L:0,P:1, sc:87, d:'A pre-layered double gold-tone strand — two chains, one clasp, zero tangling.', note:'For everyone who ever gave up untangling necklaces.' },
 { n:'Nymphe Pendant', s:'nymphe-pendant', c:'necklaces', g:'women', col:'silver', mat:SILVER, p:16.60, coll:['silver-essentials','silver-edit','for-her'], t:['organic','silver','women','modern','clean'], F:0,N:1,B:0,L:0,P:0, sc:82, d:'A freeform silver pendant with soft ripples — water, frozen mid-movement.', note:'Organic shapes pair best with crisp shirts.' },
 { n:'Esmé Necklace', s:'esme-necklace', c:'necklaces', g:'women', col:'gold', mat:GOLD, p:20.90, coll:['gold-edit','for-her','office','everyday'], t:['minimal','gold-tone','women','office','layering'], F:0,N:0,B:0,L:0,P:0, sc:84, d:'A flat paperclip-link gold-tone chain — modern, graphic, endlessly pairable.', note:'The blazer’s favourite plus-one.' },
 // ---------------- BRACELETS (15) ----------------
 { n:'Forma Bracelet', s:'forma-bracelet', c:'bracelets', g:'unisex', col:'gold', mat:GOLD, p:13.20, coll:['minimal-essentials','gold-edit','under-20','everyday','unisex','minimal-gold'], t:['cuff','minimal','gold-tone','unisex','modern'], F:0,N:0,B:0,L:0,P:0, sc:86, d:'An open gold-tone cuff with a soft rectangular profile — slips on, stays put.', note:'Cuffs should move slightly; this one moves exactly right.' },
 { n:'Noma Bracelet', s:'noma-bracelet', c:'bracelets', g:'women', col:'silver', mat:SILVER, p:10.90, coll:['silver-essentials','silver-edit','under-20'], t:['bangle','silver','women','minimal','everyday'], F:0,N:1,B:0,L:0,P:0, sc:82, d:'A featherlight silver bangle with a seamless look — stack three or wear one.', note:'The gateway bangle: start with one, end with five.' },
 { n:'Rivière Bracelet', s:'riviere-bracelet', c:'bracelets', g:'women', col:'gold', mat:GOLD, p:22.90, coll:['date-night','gift-edit','for-her','signature'], t:['tennis','gift','gold-tone','women','classic'], F:1,N:0,B:0,L:0,P:1, sc:86, d:'A line of gold-tone stones in a flexible setting — quiet tennis, loud enough for evening.', note:'Maximum sparkle-per-euro in the whole edit.' },
 { n:'Grain Bracelet', s:'grain-bracelet', c:'bracelets', g:'unisex', col:'gold', mat:GOLD, p:11.90, coll:['under-20','everyday','unisex'], t:['beaded','gold-tone','unisex','casual','gift'], F:0,N:0,B:1,L:0,P:0, sc:82, d:'Even gold-tone beads on elastic — the throw-on bracelet that goes with watches.', note:'Survives gym bags, beach days and borrowed wrists.' },
 { n:'Lien Cuff', s:'lien-cuff', c:'bracelets', g:'men', col:'silver', mat:SILVER, p:16.60, coll:['for-him','silver-essentials','silver-edit'], t:['cuff','men','silver','minimal','modern'], F:0,N:1,B:0,L:0,P:0, sc:83, d:'A brushed silver men’s cuff with a clean gap — weighty look, comfortable wear.', note:'Cuffs beat bracelets for most men: simpler, stronger.' },
 { n:'Onyx Cuff', s:'onyx-cuff', c:'bracelets', g:'men', col:'black', mat:BLACK, p:18.70, coll:['for-him','quiet-luxury','date-night'], t:['cuff','men','modern','bold','clean'], F:0,N:0,B:0,L:0,P:1, sc:88, d:'A black cuff with polished bevels — evening-ready and fingerprint-forgiving.', note:'The after-dark cuff: matte where it counts.' },
 { n:'Élan Bracelet', s:'elan-bracelet', c:'bracelets', g:'women', col:'gold', mat:GOLD, p:14.40, coll:['gold-edit','under-20','for-her','minimal-essentials'], t:['minimal','gold-tone','women','everyday','clean'], F:0,N:0,B:0,L:0,P:0, sc:83, d:'A fine gold-tone chain bracelet with a petite bar — wristwear that whispers.', note:'Sits beautifully beside a watch face.' },
 { n:'Odile Bangle', s:'odile-bangle', c:'bracelets', g:'women', col:'silver', mat:SILVER, p:13.75, coll:['silver-essentials','silver-edit','under-20','office'], t:['bangle','silver','women','office','classic'], F:0,N:1,B:0,L:0,P:0, sc:82, d:'A slim oval silver bangle shaped to the wrist — no rolling, no clanking.', note:'Engineered oval: proof someone thought about wrists.' },
 { n:'Yvette Bracelet', s:'yvette-bracelet', c:'bracelets', g:'women', col:'gold', mat:GOLD, p:17.90, coll:['gold-edit','for-her','gift-edit','date-night'], t:['beaded','gold-tone','women','gift','classic'], F:0,N:0,B:0,L:0,P:0, sc:84, d:'Faceted gold-tone beads with a single smooth accent — rhythm on the wrist.', note:'A gift that fits every time.' },
 { n:'Manon Bracelet', s:'manon-bracelet', c:'bracelets', g:'women', col:'silver', mat:SILVER, p:15.20, coll:['silver-essentials','silver-edit','everyday'], t:['minimal','silver','women','layering','clean'], F:0,N:0,B:0,L:0,P:0, sc:81, d:'A delicate silver link bracelet with an extender — adjusts to sleeves and seasons.', note:'The extender is the unsung hero of bracelet design.' },
 { n:'Aurette Bangle', s:'aurette-bangle', c:'bracelets', g:'women', col:'gold', mat:GOLD, p:19.50, coll:['gold-edit','statement','for-her','minimal-gold'], t:['bangle','gold-tone','women','statement','bold'], F:0,N:0,B:0,L:0,P:0, sc:85, d:'A wide polished gold-tone bangle — one-and-done wrist dressing.', note:'When the outfit is simple, let the bangle talk.' },
 { n:'Inès Bracelet', s:'ines-bracelet', c:'bracelets', g:'women', col:'white', mat:PEARL_G, p:12.75, coll:['under-20','gift-edit','for-her'], t:['pearl','women','gift','classic','date-night'], F:0,N:0,B:0,L:0,P:0, sc:81, d:'Small glass pearls knotted at intervals — softness with staying power.', note:'Pretty without preciousness.' },
 { n:'Lore Bracelet', s:'lore-bracelet', c:'bracelets', g:'women', col:'gold', mat:GOLD, p:21.90, coll:['gold-edit','date-night','best-value'], t:['minimal','gold-tone','women','date-night','classic'], F:0,N:0,B:1,L:0,P:0, sc:84, d:'A herringbone-flat gold-tone bracelet that lies perfectly smooth — a liquid-metal effect.', note:'Lies flatter than any chain here — made for shirt cuffs.' },
 { n:'Sadé Bangle', s:'sade-bangle', c:'bracelets', g:'women', col:'silver', mat:SILVER, p:14.90, coll:['silver-essentials','silver-edit','under-20','minimal-essentials'], t:['bangle','silver','women','minimalist','clean'], F:0,N:0,B:0,L:0,P:0, sc:82, d:'A square-edged silver bangle with a satin finish — modern lines, soft touch.', note:'Edges you can feel, in a good way.' },
 { n:'Vivienne Bracelet', s:'vivienne-bracelet', c:'bracelets', g:'women', col:'gold', mat:GOLD, p:27.50, coll:['gold-edit','statement','gift-edit','signature'], t:['statement','gold-tone','women','gift','bold'], F:1,N:0,B:0,L:1,P:0, sc:87, d:'Linked gold-tone plates with a vintage nod — the heirloom look, minus the heirloom price.', note:'Limited edit: old-Hollywood wrist, current-day ease.' },
 // ---------------- EARRINGS (15) ----------------
 { n:'Serein Earrings', s:'serein-earrings', c:'earrings', g:'women', col:'gold', mat:GALLOY, p:9.80, coll:['under-20','for-her','everyday','best-value'], t:['studs','gold-tone','women','minimal','office'], F:0,N:1,B:1,L:0,P:0, sc:90, d:'Tiny polished gold-tone studs with secure backs — the everyday default, perfected.', note:'If earrings had a uniform, this would be it.' },
 { n:'Petite Hoops', s:'petite-hoops', c:'earrings', g:'women', col:'gold', mat:GOLD, p:10.40, coll:['under-20','everyday','for-her','minimal-essentials'], t:['hoops','gold-tone','women','everyday','casual'], F:0,N:0,B:0,L:0,P:0, sc:83, d:'Small everyday gold-tone hoops with a seamless click — in and out in seconds.', note:'The 10-second upgrade to any outfit.' },
 { n:'Halo Hoops', s:'halo-hoops', c:'earrings', g:'women', col:'silver', mat:SILVER, p:12.90, coll:['silver-essentials','silver-edit','everyday'], t:['hoops','silver','women','minimal','casual'], F:0,N:0,B:0,L:0,P:0, sc:80, d:'Lightweight silver hoops with a high-shine finish — all-day comfort, all-evening shine.', note:'Hoops heavy enough to see, light enough to forget.' },
 { n:'Ivoire Studs', s:'ivoire-studs', c:'earrings', g:'women', col:'silver', mat:SALLOY, p:7.90, coll:['under-20','best-value','silver-essentials','silver-edit'], t:['studs','silver','women','minimal','office'], F:0,N:0,B:1,L:0,P:0, sc:82, d:'Petite ivory-toned studs on silver posts — soft focus for the face.', note:'The cheapest piece here, and nobody would guess.' },
 { n:'Perle Studs', s:'perle-studs', c:'earrings', g:'women', col:'white', mat:PEARL_G, p:9.20, coll:['under-20','gift-edit','for-her'], t:['pearl','women','gift','classic','minimal'], F:0,N:0,B:0,L:0,P:0, sc:81, d:'Classic glass-pearl studs with a warm lustre — the gift-drawer staple.', note:'Some classics earn their status; these did.' },
 { n:'Céleste Hoops', s:'celeste-hoops', c:'earrings', g:'women', col:'gold', mat:GOLD, p:16.90, coll:['gold-edit','for-her','date-night','statement'], t:['hoops','gold-tone','women','statement','date-night'], F:0,N:1,B:0,L:0,P:1, sc:88, d:'Medium sculpted gold-tone hoops with presence — frames the face in any light.', note:'An editor’s pick for good reason: the proportions are perfect.' },
 { n:'Iris Studs', s:'iris-studs', c:'earrings', g:'women', col:'silver', mat:SALLOY, p:8.50, coll:['under-20','silver-edit','office','minimal-essentials'], t:['studs','silver','women','office','minimalist'], F:0,N:0,B:0,L:0,P:0, sc:80, d:'Flat-disc silver studs with a mirror face — crisp, tiny, exact.', note:'Precision studs for precision dressers.' },
 { n:'Ona Hoops', s:'ona-hoops', c:'earrings', g:'unisex', col:'silver', mat:SILVER, p:11.20, coll:['unisex','silver-edit','everyday','under-20'], t:['hoops','silver','unisex','casual','minimal'], F:0,N:0,B:0,L:0,P:0, sc:81, d:'Small seamless silver hoops cut for any ear — unisex by design, not by compromise.', note:'One hoop, every wardrobe.' },
 { n:'Lucienne Drops', s:'lucienne-drops', c:'earrings', g:'women', col:'gold', mat:GALLOY, p:19.90, coll:['gold-edit','date-night','statement','signature','for-her'], t:['drops','gold-tone','women','statement','date-night'], F:1,N:0,B:0,L:0,P:1, sc:89, d:'Articulated gold-tone drops that move when you do — evening earrings with manners.', note:'Movement is the luxury here; they catch light with every turn.' },
 { n:'Nymphe Earrings', s:'nymphe-earrings', c:'earrings', g:'women', col:'silver', mat:SALLOY, p:13.40, coll:['silver-essentials','silver-edit','for-her'], t:['sculptural','silver','women','modern','clean'], F:0,N:1,B:0,L:0,P:0, sc:82, d:'Small wave-formed silver earrings — organic sculpture at stud scale.', note:'Wearable art that still makes the 8am meeting.' },
 { n:'Esmé Huggies', s:'esme-huggies', c:'earrings', g:'women', col:'gold', mat:GOLD, p:14.60, coll:['gold-edit','everyday','for-her'], t:['huggies','gold-tone','women','everyday','minimal'], F:0,N:0,B:0,L:0,P:0, sc:83, d:'Close-hugging gold-tone hoops with a smooth hinge — sleep-in-them comfortable.', note:'The low-maintenance hoop for high-maintenance schedules.' },
 { n:'Alba Studs', s:'alba-studs', c:'earrings', g:'women', col:'silver', mat:SALLOY, p:9.50, coll:['under-20','silver-edit','office'], t:['studs','silver','women','office','classic'], F:0,N:0,B:1,L:0,P:0, sc:81, d:'Polished silver ball studs in a versatile mid size — the second-earring essential.', note:'Second holes finally get their moment.' },
 { n:'Odette Drops', s:'odette-drops', c:'earrings', g:'women', col:'gold', mat:GALLOY, p:21.90, coll:['gold-edit','statement','date-night','signature'], t:['drops','gold-tone','women','bold','date-night'], F:1,N:0,B:0,L:0,P:1, sc:87, d:'Long linear gold-tone drops with a brushed finish — vertical lines, elongating effect.', note:'Earrings that do what good tailoring does: lengthen.' },
 { n:'Noor Hoops', s:'noor-hoops', c:'earrings', g:'women', col:'silver', mat:SILVER, p:15.90, coll:['silver-essentials','silver-edit','statement'], t:['hoops','silver','women','bold','modern'], F:0,N:0,B:0,L:0,P:0, sc:83, d:'Bold rounded silver hoops with a molten-soft surface — statement weight, feather feel.', note:'Big-hoop drama without the earlobe regret.' },
 { n:'Fable Studs', s:'fable-studs', c:'earrings', g:'women', col:'black', mat:'Black ion-plated alloy, nickel-free posts', p:8.90, coll:['under-20','quiet-luxury','minimal-essentials'], t:['studs','women','minimal','modern','clean'], F:0,N:1,B:0,L:0,P:0, sc:80, d:'Matte black micro-studs — the quietest statement in the drawer.', note:'For minimalists who find even silver too shiny some days.' },
 // ---------------- CHAINS (10) ----------------
 { n:'Aurelia Chain', s:'aurelia-chain', c:'chains', g:'women', col:'gold', mat:GOLD, p:17.42, coll:['minimal-essentials','gold-edit','under-20','for-her','best-value','signature','minimal-gold'], t:['chain','layering','gold-tone','women','classic'], F:1,N:0,B:1,L:0,P:1, sc:94, d:'The perfect mid-weight gold-tone chain — even links, soft shine, endless pairings.', note:'If the edit had a mascot, it would be this chain.' },
 { n:'Chaîne Fine', s:'chaine-fine', c:'chains', g:'unisex', col:'gold', mat:GOLD, p:15.60, coll:['minimal-essentials','gold-edit','everyday','unisex'], t:['chain','gold-tone','unisex','layering','minimal'], F:0,N:1,B:0,L:0,P:0, sc:84, d:'A whisper-fine unisex gold-tone chain — the base layer every stack starts from.', note:'Start every stack here; end it wherever you like.' },
 { n:'Chaîne Gourmette', s:'chaine-gourmette', c:'chains', g:'unisex', col:'silver', mat:SILVER, p:21.90, coll:['silver-essentials','silver-edit','everyday','unisex'], t:['chain','silver','unisex','classic','casual'], F:0,N:0,B:0,L:0,P:0, sc:82, d:'A classic curb-link silver chain with real hand-feel — unisex and unbothered.', note:'The chain equivalent of good denim.' },
 { n:'Élan Chain', s:'elan-chain', c:'chains', g:'men', col:'silver', mat:SILVER, p:19.90, coll:['for-him','silver-essentials','silver-edit','under-20'], t:['chain','men','silver','minimal','casual'], F:0,N:0,B:1,L:0,P:0, sc:87, d:'A clean Cuban-style silver chain cut for men — presence without pendants.', note:'Solo-chain confidence: no pendant required.' },
 { n:'Maillon Chain', s:'maillon-chain', c:'chains', g:'men', col:'gold', mat:GOLD, p:24.90, coll:['for-him','date-night','gold-edit'], t:['chain','men','gold-tone','bold','statement'], F:0,N:0,B:0,L:0,P:0, sc:84, d:'A bolder gold-tone link chain for open collars and evening layers.', note:'Wears best with confidence and an unbuttoned collar.' },
 { n:'Solenne Chain', s:'solenne-chain', c:'chains', g:'women', col:'gold', mat:GOLD, p:29.90, coll:['gold-edit','statement','signature','for-her'], t:['chain','gold-tone','women','statement','bold'], F:1,N:0,B:0,L:0,P:1, sc:90, d:'A substantial twisted gold-tone chain — the standalone necklace that needs nothing else.', note:'One chain, one neckline, done.' },
 { n:'Vesper Chain', s:'vesper-chain', c:'chains', g:'women', col:'silver', mat:SILVER, p:18.40, coll:['silver-essentials','silver-edit','layering','for-her'], t:['chain','silver','women','layering','modern'], F:0,N:1,B:0,L:0,P:0, sc:83, d:'A fluid snake-style silver chain that pours over collarbones — made for layering.', note:'Liquid silver: the layering piece that never tangles.' },
 { n:'Lore Chain', s:'lore-chain', c:'chains', g:'women', col:'gold', mat:GOLD, p:22.50, coll:['gold-edit','for-her','office','everyday'], t:['chain','gold-tone','women','office','classic'], F:0,N:0,B:0,L:0,P:0, sc:83, d:'A neat cable-link gold-tone chain at a desk-friendly length — polish, calibrated.', note:'Boardroom to bistro without changing a thing.' },
 { n:'Isolde Chain', s:'isolde-chain', c:'chains', g:'women', col:'gold', mat:GOLD, p:34.90, coll:['gold-edit','statement','gift-edit'], t:['chain','gold-tone','women','statement','gift'], F:0,N:0,B:0,L:1,P:0, sc:86, d:'A hand-feel-rich gold-tone chain with alternating links — limited edit, lasting impression.', note:'Limited edit: the special-occasion chain.' },
 { n:'Manon Chain', s:'manon-chain', c:'chains', g:'women', col:'silver', mat:SILVER, p:16.20, coll:['silver-essentials','silver-edit','under-20','minimal-essentials'], t:['chain','silver','women','minimal','everyday'], F:0,N:0,B:0,L:0,P:0, sc:81, d:'A petite silver trace chain — the minimalist’s daily default.', note:'Small chain, big wardrobe compatibility.' },
 // ---------------- DEV TEST PRODUCT ----------------
 { n:'Mock Gold Ring', s:'mock-gold-ring', c:'rings', g:'unisex', col:'gold', mat:'Gold-tone stainless steel (demo)', p:12.00, coll:['new-arrivals','under-20','new-finds','unisex'], t:['demo','test','minimal'], F:0,N:1,B:0,L:0,P:0, sc:75, d:'Development test product used to verify the affiliate click path end to end.', note:'A test record: verifies that SHOP ON ALIEXPRESS navigates to the configured URL.' },
 // ---------------- MEN'S LINE (10) ----------------
 { n:'Cassius Signet', s:'cassius-signet', c:'rings', g:'men', col:'black', mat:BLACK, p:22.90, coll:['for-him','quiet-luxury','new-arrivals','statement'], t:['signet','men','bold','modern','date-night'], F:0,N:1,B:0,L:0,P:0, sc:86, d:'A broad black signet with a mirror-polished face — modern armor for the hand.', note:'Wears like confidence: best with rolled sleeves.' },
 { n:'Octave Band', s:'octave-band', c:'rings', g:'men', col:'silver', mat:SILVER, p:17.50, coll:['for-him','silver-edit','silver-essentials','minimal-essentials'], t:['band','men','silver','minimal','office'], F:0,N:0,B:0,L:0,P:0, sc:83, d:'An eight-millimetre silver band with brushed sides — the wedding-band silhouette, casualised.', note:'Understated enough for every day, finished enough for events.' },
 { n:'Sorel Chain', s:'sorel-chain', c:'chains', g:'men', col:'black', mat:BLACK, p:26.40, coll:['for-him','statement','new-arrivals'], t:['chain','men','bold','modern','statement'], F:0,N:1,B:0,L:0,P:0, sc:85, d:'A matte black curb chain with real weight — streetwear polish without pendants.', note:'Let it sit on black; let black do the rest.' },
 { n:'Bram Pendant', s:'bram-pendant', c:'necklaces', g:'men', col:'silver', mat:SILVER, p:23.90, coll:['for-him','silver-edit','gift-edit','date-night'], t:['pendant','men','silver','gift','classic'], F:0,N:0,B:0,L:0,P:0, sc:84, d:'A rectangular silver pendant with softened corners on a box chain — quiet luxury, cut for men.', note:'The pendant for men who thought pendants weren’t for them.' },
 { n:'Ivo Cuff', s:'ivo-cuff', c:'bracelets', g:'men', col:'silver', mat:SILVER, p:19.75, coll:['for-him','silver-edit','minimal-essentials','everyday'], t:['cuff','men','silver','minimal','casual'], F:0,N:0,B:1,L:0,P:0, sc:84, d:'A slim hammered silver cuff — texture that reads handmade, price that reads sensible.', note:'Hammered finishes hide a multitude of sins.' },
 { n:'Ludo Ring', s:'ludo-ring', c:'rings', g:'men', col:'gold', mat:GOLD, p:18.20, coll:['for-him','gold-edit','minimal-gold','gift-edit'], t:['band','men','gold-tone','gift','classic'], F:0,N:0,B:0,L:0,P:0, sc:82, d:'A warm gold-tone men’s band with a comfort-fit interior — easy from day one.', note:'Comfort-fit means you’ll actually keep it on.' },
 { n:'Nils Bracelet', s:'nils-bracelet', c:'bracelets', g:'men', col:'black', mat:BLACK, p:16.90, coll:['for-him','under-20','everyday','quiet-luxury'], t:['minimal','men','casual','everyday','clean'], F:0,N:1,B:0,L:0,P:0, sc:83, d:'Black beads with a single steel accent on elastic — the minimalist men’s bracelet.', note:'One accent bead: restraint you can count.' },
 { n:'Ezra Chain', s:'ezra-chain', c:'chains', g:'men', col:'silver', mat:SILVER, p:27.90, coll:['for-him','silver-edit','statement','gift-edit'], t:['chain','men','silver','statement','gift'], F:0,N:0,B:0,L:0,P:1, sc:87, d:'A rope-twist silver chain with a satisfying heft — the chain that finishes an outfit.', note:'An editor’s pick from the men’s line: twist catches light beautifully.' },
 { n:'Paul Pendant', s:'paul-pendant', c:'necklaces', g:'men', col:'black', mat:BLACK, p:21.20, coll:['for-him','quiet-luxury','date-night'], t:['pendant','men','modern','date-night','clean'], F:0,N:0,B:0,L:1,P:0, sc:85, d:'A black stone-look pendant in a slim steel frame — gallery minimalism for the neck.', note:'Limited edit: severe in the best way.' },
 { n:'Rémy Band', s:'remy-band', c:'rings', g:'men', col:'black', mat:BLACK, p:15.40, coll:['for-him','under-20','minimal-essentials','everyday'], t:['band','men','minimal','casual','clean'], F:0,N:0,B:0,L:0,P:0, sc:81, d:'A flat-profile black band with polished edges — the everyday men’s ring, solved.', note:'Edges polished, routine uninterrupted.' },
 // ---------------- UNISEX LINE (9 + mock = 10) ----------------
 { n:'Ave Chain', s:'ave-chain', c:'chains', g:'unisex', col:'gold', mat:GOLD, p:20.50, coll:['unisex','gold-edit','layering','new-arrivals'], t:['chain','gold-tone','unisex','layering','modern'], F:0,N:1,B:0,L:0,P:0, sc:84, d:'A mid-fine gold-tone chain tuned for sharing — sits well at any length on anyone.', note:'Borrowed, lent, re-borrowed: sharing looks good.' },
 { n:'Kit Ring', s:'kit-ring', c:'rings', g:'unisex', col:'silver', mat:SILVER, p:13.90, coll:['unisex','silver-edit','under-20','minimal-essentials'], t:['band','silver','unisex','minimal','casual'], F:0,N:0,B:0,L:0,P:0, sc:82, d:'A smooth D-profile silver band in a shareable width — the household ring.', note:'One ring, two bedside tables.' },
 { n:'Lou Bracelet', s:'lou-bracelet', c:'bracelets', g:'unisex', col:'silver', mat:SILVER, p:14.75, coll:['unisex','silver-edit','everyday','gift-edit'], t:['minimal','silver','unisex','gift','casual'], F:0,N:0,B:0,L:0,P:0, sc:82, d:'A fine silver box-chain bracelet with a slide clasp — adjustable, giftable, keepable.', note:'The slide clasp means it fits whoever opens it.' },
 { n:'Noa Pendant', s:'noa-pendant', c:'necklaces', g:'unisex', col:'silver', mat:SILVER, p:16.40, coll:['unisex','silver-edit','minimal-essentials','everyday'], t:['pendant','silver','unisex','minimal','clean'], F:0,N:1,B:0,L:0,P:0, sc:83, d:'A small silver arch pendant — a doorway, a rainbow, a shrug: interpret freely.', note:'Ambiguity is the design here.' },
 { n:'Rue Hoops', s:'rue-hoops', c:'earrings', g:'unisex', col:'gold', mat:GOLD, p:12.90, coll:['unisex','gold-edit','under-20','everyday'], t:['hoops','gold-tone','unisex','casual','minimal'], F:0,N:0,B:1,L:0,P:0, sc:83, d:'Compact gold-tone hoops with a hinge that clicks — unisex ears, rejoice.', note:'Small hoops, broad appeal.' },
 { n:'Sam Cuff', s:'sam-cuff', c:'bracelets', g:'unisex', col:'black', mat:BLACK, p:17.20, coll:['unisex','quiet-luxury','minimal-essentials'], t:['cuff','unisex','modern','clean','casual'], F:0,N:0,B:0,L:0,P:0, sc:82, d:'A narrow black cuff with a brushed finish — the shared-drawer staple.', note:'Narrow enough to stack, strong enough solo.' },
 { n:'Ted Band', s:'ted-band', c:'rings', g:'unisex', col:'gold', mat:GOLD, p:11.60, coll:['unisex','gold-edit','under-20','minimal-gold'], t:['band','gold-tone','unisex','minimal','gift'], F:0,N:0,B:0,L:0,P:0, sc:81, d:'A slim polished gold-tone band — the plus-one for any finger.', note:'Goes with the other ring you already wear.' },
 { n:'Ulysse Chain', s:'ulysse-chain', c:'chains', g:'unisex', col:'silver', mat:SILVER, p:23.20, coll:['unisex','silver-edit','statement','new-arrivals'], t:['chain','silver','unisex','statement','bold'], F:0,N:1,B:0,L:0,P:0, sc:85, d:'A mariner-link silver chain with an odyssey-grade clasp — adventure-adjacent.', note:'Mariner links: the sailor stripe of jewelry.' },
 { n:'Wren Studs', s:'wren-studs', c:'earrings', g:'unisex', col:'silver', mat:SALLOY, p:9.90, coll:['unisex','silver-edit','under-20','minimal-essentials'], t:['studs','silver','unisex','minimal','casual'], F:0,N:0,B:0,L:0,P:0, sc:80, d:'Tiny silver dome studs — the smallest thing here, and quietly the most versatile.', note:'Small studs, zero decisions.' },
];

export { R as ROWS };
